<?php /* Smarty version 2.6.26, created on 2010-02-13 13:10:33
         compiled from rss/groups.tpl */

$this->_cache_serials['./Smarty/templates_c/%%0C^0CB^0CBF546B%%groups.tpl.inc'] = '297257adb357ac9239d3408f506a0567';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'rss/groups.tpl', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_297257adb357ac9239d3408f506a0567_0(&$this)
{
echo translate_smarty(array('id' => 'rss_groups_finished','round' => $this->_tpl_vars['item']['roundNum']), $this);
}


function _smarty_tplfunc_297257adb357ac9239d3408f506a0567_1(&$this)
{
echo translate_smarty(array('id' => 'rss_groups_finished_text','round' => $this->_tpl_vars['item']['roundNum']), $this);
}



?>
