<?php /* Smarty version 2.6.26, created on 2010-02-15 15:55:50
         compiled from managelevels.tpl */

$this->_cache_serials['./Smarty/templates_c/%%19^19E^19EBBE75%%managelevels.tpl.inc'] = '0047d5faa6cff2ff93323bffbb8b2a93';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'managelevels.tpl', 22, false),array('function', 'url', 'managelevels.tpl', 25, false),array('modifier', 'escape', 'managelevels.tpl', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'managelevels_title'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_1(&$this)
{
echo url_smarty(array('page' => 'editlevel','id' => 'new'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_2(&$this)
{
echo translate_smarty(array('id' => 'new_level'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_3(&$this)
{
echo translate_smarty(array('id' => 'name'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_4(&$this)
{
echo translate_smarty(array('id' => 'scorecalculation'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_5(&$this)
{
echo translate_smarty(array('id' => 'available'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_6(&$this)
{
echo translate_smarty(array('id' => 'edit'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_7(&$this)
{
echo translate_smarty(array('id' => 'yes_'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_8(&$this)
{
echo translate_smarty(array('id' => 'no_'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_9(&$this)
{
echo url_smarty(array('page' => 'editlevel','id' => $this->_tpl_vars['class']->id), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_10(&$this)
{
echo translate_smarty(array('id' => 'edit'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_11(&$this)
{
echo url_smarty(array('page' => 'editlevel','id' => 'new'), $this);
}


function _smarty_tplfunc_0047d5faa6cff2ff93323bffbb8b2a93_12(&$this)
{
echo translate_smarty(array('id' => 'new_level'), $this);
}



?>
