<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:08
         compiled from include/breadcrumb.tpl */

$this->_cache_serials['./Smarty/templates_c/%%19^197^1976EDC1%%breadcrumb.tpl.inc'] = '02aebd15d3532717aaa595e6ca9ebc6b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'include/breadcrumb.tpl', 23, false),array('function', 'url', 'include/breadcrumb.tpl', 33, false),)), $this); ?>
<?php
function _smarty_tplfunc_02aebd15d3532717aaa595e6ca9ebc6b_0(&$this)
{
echo url_smarty(array('arguments' => $this->_tpl_vars['from']['link']), $this);
}



?>
