<?php /* Smarty version 2.6.26, created on 2010-02-16 14:51:11
         compiled from javascript/live.tpl */

$this->_cache_serials['./Smarty/templates_c/%%29^294^294A0ACE%%live.tpl.inc'] = '69d9cd2aafd6224c4f98e0074b1b8b3a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'javascript/live.tpl', 56, false),array('function', 'translate', 'javascript/live.tpl', 85, false),)), $this); ?>
<?php
function _smarty_tplfunc_69d9cd2aafd6224c4f98e0074b1b8b3a_0(&$this)
{
echo url_smarty(array('page' => 'liveresultdata'), $this);
}


function _smarty_tplfunc_69d9cd2aafd6224c4f98e0074b1b8b3a_1(&$this)
{
echo translate_smarty(array('id' => 'live_update_failing'), $this);
}



?>
