<?php /* Smarty version 2.6.26, created on 2010-02-15 15:55:52
         compiled from editlevel.tpl */

$this->_cache_serials['./Smarty/templates_c/%%32^32F^32F68438%%editlevel.tpl.inc'] = 'f6f2d0df51d627a15402121b4ad892da';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editlevel.tpl', 22, false),array('function', 'formerror', 'editlevel.tpl', 34, false),array('function', 'html_options', 'editlevel.tpl', 40, false),array('modifier', 'escape', 'editlevel.tpl', 33, false),)), $this); ?>
<?php
function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'editlevel_title'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_1(&$this)
{
echo translate_smarty(array('id' => 'editlevel_title'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_2(&$this)
{
echo translate_smarty(array('id' => 'name'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_3(&$this)
{
echo formerror_smarty(array('field' => 'name'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_4(&$this)
{
echo translate_smarty(array('id' => 'scorecalculation'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_5(&$this)
{
echo translate_smarty(array('id' => 'available'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_6(&$this)
{
echo translate_smarty(array('id' => 'form_save'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_7(&$this)
{
echo translate_smarty(array('id' => 'form_cancel'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_8(&$this)
{
echo translate_smarty(array('id' => 'delete_level'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_9(&$this)
{
echo translate_smarty(array('id' => 'can_delete_level'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_10(&$this)
{
echo translate_smarty(array('id' => 'delete'), $this);
}


function _smarty_tplfunc_f6f2d0df51d627a15402121b4ad892da_11(&$this)
{
echo translate_smarty(array('id' => 'cant_delete_level'), $this);
}



?>
