<?php /* Smarty version 2.6.26, created on 2010-02-17 19:13:16
         compiled from splitclasses.tpl */

$this->_cache_serials['./Smarty/templates_c/%%3C^3C8^3C84773C%%splitclasses.tpl.inc'] = 'cc48fb93c7a5dcbb172f0c287f2fd2b3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'splitclasses.tpl', 22, false),array('function', 'initializeGetFormFields', 'splitclasses.tpl', 107, false),array('function', 'counter', 'splitclasses.tpl', 151, false),array('modifier', 'escape', 'splitclasses.tpl', 138, false),)), $this); ?>
<?php
function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_0(&$_smarty)
{
echo translate_smarty(array('id' => 'splitclasses_title','assign' => 'title'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_1(&$_smarty)
{
echo initializeGetFormFields_Smarty(array('regenerate' => false), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_2(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_section_text_2'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_3(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_sections'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_4(&$_smarty)
{
echo initializeGetFormFields_Smarty(array('regenerate' => false), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_5(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_section_text_1'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_6(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_sections'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_7(&$_smarty)
{
echo translate_smarty(array('id' => 'split_classes_quickhelp'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_8(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_9(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_10(&$_smarty)
{
echo translate_smarty(array('id' => 'split'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_11(&$_smarty)
{
echo translate_smarty(array('id' => 'combine'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_12(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_13(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_14(&$_smarty)
{
echo translate_smarty(array('id' => 'enter_split_name'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_15(&$_smarty)
{
echo translate_smarty(array('id' => 'new_split_name'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_16(&$_smarty)
{
echo translate_smarty(array('id' => 'split'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_17(&$_smarty)
{
echo translate_smarty(array('id' => 'combine'), $_smarty);
}


function _smarty_tplfunc_cc48fb93c7a5dcbb172f0c287f2fd2b3_18(&$_smarty)
{
echo translate_smarty(array('id' => 'cant_move_between_classes'), $_smarty);
}



?>
