<?php /* Smarty version 2.6.26, created on 2010-02-15 16:10:36
         compiled from editmyinfo.tpl */

$this->_cache_serials['./Smarty/templates_c/%%3D^3D5^3D5A691A%%editmyinfo.tpl.inc'] = '1816168db8fc7f7dfcffa70d8df51335';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editmyinfo.tpl', 22, false),array('function', 'formerror', 'editmyinfo.tpl', 34, false),array('function', 'html_select_date', 'editmyinfo.tpl', 65, false),array('modifier', 'escape', 'editmyinfo.tpl', 33, false),)), $this); ?>
<?php
function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_0(&$this)
{
echo translate_smarty(array('id' => 'editmyinfo_title','assign' => 'title'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_1(&$this)
{
echo translate_smarty(array('id' => 'reg_contact_info'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_2(&$this)
{
echo translate_smarty(array('id' => 'last_name'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_3(&$this)
{
echo formerror_smarty(array('field' => 'lastname'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_4(&$this)
{
echo translate_smarty(array('id' => 'first_name'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_5(&$this)
{
echo formerror_smarty(array('field' => 'firstname'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_6(&$this)
{
echo translate_smarty(array('id' => 'reg_email'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_7(&$this)
{
echo formerror_smarty(array('field' => 'email'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_8(&$this)
{
echo translate_smarty(array('id' => 'reg_player_info'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_9(&$this)
{
echo translate_smarty(array('id' => 'pdga_number'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_10(&$this)
{
echo formerror_smarty(array('field' => 'pdga'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_11(&$this)
{
echo translate_smarty(array('id' => 'gender'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_12(&$this)
{
echo translate_smarty(array('id' => 'male'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_13(&$this)
{
echo translate_smarty(array('id' => 'female'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_14(&$this)
{
echo formerror_smarty(array('field' => 'gender'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_15(&$this)
{
echo translate_smarty(array('id' => 'dob'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_16(&$this)
{
echo translate_smarty(array('id' => 'year_default','assign' => 'year_default'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_17(&$this)
{
echo formerror_smarty(array('field' => 'dob'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_18(&$this)
{
echo translate_smarty(array('id' => 'form_save'), $this);
}


function _smarty_tplfunc_1816168db8fc7f7dfcffa70d8df51335_19(&$this)
{
echo translate_smarty(array('id' => 'form_cancel'), $this);
}



?>
