<?php /* Smarty version 2.6.26, created on 2010-01-30 09:24:41
         compiled from help.tpl */

$this->_cache_serials['./Smarty/templates_c/%%41^416^416864CF%%help.tpl.inc'] = '257205f6372f78638e0ff11630a04fc3';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'help.tpl', 13, false),)), $this); ?>
<?php
function _smarty_tplfunc_257205f6372f78638e0ff11630a04fc3_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'help_title'), $this);
}



?>
