<?php /* Smarty version 2.6.26, created on 2010-02-18 19:25:27
         compiled from eventviews/cancelsignup.tpl */

$this->_cache_serials['./Smarty/templates_c/%%42^421^4211ABCC%%cancelsignup.tpl.inc'] = '2aeba0b9604dea70014a8ed4d7305f68';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'eventviews/cancelsignup.tpl', 29, false),)), $this); ?>
<?php
function _smarty_tplfunc_2aeba0b9604dea70014a8ed4d7305f68_0(&$this)
{
echo translate_smarty(array('id' => 'cant_cancel_signup_now'), $this);
}


function _smarty_tplfunc_2aeba0b9604dea70014a8ed4d7305f68_1(&$this)
{
echo translate_smarty(array('id' => 'signed_up_and_paid'), $this);
}


function _smarty_tplfunc_2aeba0b9604dea70014a8ed4d7305f68_2(&$this)
{
echo translate_smarty(array('id' => 'signed_up_not_paid'), $this);
}


function _smarty_tplfunc_2aeba0b9604dea70014a8ed4d7305f68_3(&$this)
{
echo translate_smarty(array('id' => 'cancelsignup'), $this);
}


function _smarty_tplfunc_2aeba0b9604dea70014a8ed4d7305f68_4(&$this)
{
echo translate_smarty(array('id' => 'abort'), $this);
}



?>
