<?php /* Smarty version 2.6.26, created on 2010-02-16 13:09:28
         compiled from editeventpage.tpl */

$this->_cache_serials['./Smarty/templates_c/%%42^428^428E69CE%%editeventpage.tpl.inc'] = '38a474a454cc019c8fff8a4821501680';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editeventpage.tpl', 41, false),array('modifier', 'escape', 'editeventpage.tpl', 51, false),)), $this); ?>
<?php
function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'editcontentpage_title'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_1(&$_smarty)
{
echo translate_smarty(array('id' => 'title'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_2(&$_smarty)
{
echo translate_smarty(array('assign' => 'pagetitle','id' => $_smarty->_tpl_vars['transkey']), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_3(&$_smarty)
{
echo translate_smarty(array('id' => 'default_title_for_page','title' => $_smarty->_tpl_vars['pagetitle']), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_4(&$_smarty)
{
echo translate_smarty(array('id' => 'content'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_5(&$_smarty)
{
echo translate_smarty(array('id' => 'content_access'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_6(&$_smarty)
{
echo translate_smarty(array('id' => 'access_all'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_7(&$_smarty)
{
echo translate_smarty(array('id' => 'access_management'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_8(&$_smarty)
{
echo translate_smarty(array('id' => 'access_admin'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_9(&$_smarty)
{
echo translate_smarty(array('id' => 'form_save'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_10(&$_smarty)
{
echo translate_smarty(array('id' => 'form_preview'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_11(&$_smarty)
{
echo translate_smarty(array('id' => 'form_cancel'), $_smarty);
}


function _smarty_tplfunc_38a474a454cc019c8fff8a4821501680_12(&$_smarty)
{
echo translate_smarty(array('id' => 'delete'), $_smarty);
}



?>
