<?php /* Smarty version 2.6.26, created on 2010-02-13 18:28:55
         compiled from manage_users.tpl */

$this->_cache_serials['./Smarty/templates_c/%%47^47D^47D3A8B0%%manage_users.tpl.inc'] = 'a971dd33098a87f5c7f83c9b81b12a9a';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'manage_users.tpl', 25, false),array('function', 'submenulinks', 'manage_users.tpl', 27, false),)), $this); ?>
<?php
function _smarty_tplfunc_a971dd33098a87f5c7f83c9b81b12a9a_0(&$this)
{
echo translate_smarty(array('id' => 'admin_main_text'), $this);
}



?>
