<?php /* Smarty version 2.6.26, created on 2010-02-15 16:26:49
         compiled from include/header.tpl */

$this->_cache_serials['./Smarty/templates_c/%%4C^4C3^4C3A410D%%header.tpl.inc'] = 'dc8b3e6d951d0e301b8534c0c8fb1716';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'include/header.tpl', 27, false),)), $this); ?>
<?php
function _smarty_tplfunc_dc8b3e6d951d0e301b8534c0c8fb1716_0(&$this)
{
echo translate_smarty(array('id' => 'site_name'), $this);
}


function _smarty_tplfunc_dc8b3e6d951d0e301b8534c0c8fb1716_1(&$this)
{
echo translate_smarty(array('id' => 'site_name'), $this);
}


function _smarty_tplfunc_dc8b3e6d951d0e301b8534c0c8fb1716_2(&$this)
{
echo translate_smarty(array('id' => 'site_name_long'), $this);
}



?>
