<?php /* Smarty version 2.6.26, created on 2010-02-16 14:51:09
         compiled from eventviews/results.tpl */

$this->_cache_serials['./Smarty/templates_c/%%54^54E^54E3D072%%results.tpl.inc'] = '75fabe38e7412e30a013507bb43be8a2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'eventviews/results.tpl', 106, false),array('function', 'math', 'eventviews/results.tpl', 108, false),array('function', 'translate', 'eventviews/results.tpl', 113, false),array('function', 'url', 'eventviews/results.tpl', 117, false),array('function', 'counter', 'eventviews/results.tpl', 139, false),)), $this); ?>
<?php
function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_0(&$this)
{
echo translate_smarty(array('id' => 'round_title','number' => $this->_tpl_vars['roundnum']), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_1(&$this)
{
echo url_smarty(array('page' => 'event','id' => $_GET['id'],'view' => $_GET['view'],'round' => $this->_tpl_vars['roundnum']), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_2(&$this)
{
echo translate_smarty(array('id' => 'round_title','number' => $this->_tpl_vars['roundnum']), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_3(&$this)
{
echo translate_smarty(array('id' => 'result_pos'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_4(&$this)
{
echo translate_smarty(array('id' => 'result_name'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_5(&$this)
{
echo translate_smarty(array('id' => 'result_score'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_6(&$this)
{
echo translate_smarty(array('id' => 'round'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_7(&$this)
{
echo translate_smarty(array('id' => 'cumulative'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_8(&$this)
{
echo translate_smarty(array('id' => 'hole_num'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_9(&$this)
{
echo translate_smarty(array('id' => 'hole_par'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_10(&$this)
{
echo translate_smarty(array('id' => 'hole_out'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_11(&$this)
{
echo translate_smarty(array('id' => 'hole_in'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_12(&$this)
{
echo translate_smarty(array('id' => 'result'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_13(&$this)
{
echo translate_smarty(array('id' => 'result'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_14(&$this)
{
echo translate_smarty(array('id' => 'result_dnf'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_15(&$this)
{
echo translate_smarty(array('id' => 'result_dnf'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_16(&$this)
{
echo translate_smarty(array('id' => 'result_dnf'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_17(&$this)
{
echo translate_smarty(array('id' => 'result_dnf'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_18(&$this)
{
echo translate_smarty(array('id' => 'result_dnf'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_19(&$this)
{
echo translate_smarty(array('id' => 'result_dnf'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_20(&$this)
{
echo translate_smarty(array('id' => 'result_penalty_panel'), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_21(&$this)
{
echo url_smarty(array('page' => "javascript/live"), $this);
}


function _smarty_tplfunc_75fabe38e7412e30a013507bb43be8a2_22(&$this)
{
echo translate_smarty(array('id' => 'result_penalty_panel'), $this);
}



?>
