<?php /* Smarty version 2.6.26, created on 2010-01-30 09:24:42
         compiled from help/events.tpl */

$this->_cache_serials['./Smarty/templates_c/%%56^566^56678747%%events.tpl.inc'] = 'c9c50214476b802f92ddf02e1f121eda';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'helplink', 'help/events.tpl', 3, false),)), $this); ?>
<?php
function _smarty_tplfunc_c9c50214476b802f92ddf02e1f121eda_0(&$this)
{
echo helplink_smarty(array('page' => 'users','title' => 'käyttäjiin'), $this);
}



?>
