<?php /* Smarty version 2.6.26, created on 2010-02-19 13:53:03
         compiled from recoverpassword.tpl */

$this->_cache_serials['./Smarty/templates_c/%%5C^5CB^5CBA9BBC%%recoverpassword.tpl.inc'] = '7f1534ba81dabfb1d16c96c3e5b581b2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'recoverpassword.tpl', 22, false),array('modifier', 'escape', 'recoverpassword.tpl', 38, false),)), $this); ?>
<?php
function _smarty_tplfunc_7f1534ba81dabfb1d16c96c3e5b581b2_0(&$this)
{
echo translate_smarty(array('id' => 'recoverpassword_title','assign' => 'title'), $this);
}


function _smarty_tplfunc_7f1534ba81dabfb1d16c96c3e5b581b2_1(&$this)
{
echo translate_smarty(array('id' => 'error_no_such_user'), $this);
}


function _smarty_tplfunc_7f1534ba81dabfb1d16c96c3e5b581b2_2(&$this)
{
echo translate_smarty(array('id' => 'recover_password_help'), $this);
}


function _smarty_tplfunc_7f1534ba81dabfb1d16c96c3e5b581b2_3(&$this)
{
echo translate_smarty(array('id' => 'username_or_email'), $this);
}


function _smarty_tplfunc_7f1534ba81dabfb1d16c96c3e5b581b2_4(&$this)
{
echo translate_smarty(array('id' => 'recover'), $this);
}



?>
