<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:26
         compiled from admin.tpl */

$this->_cache_serials['./Smarty/templates_c/%%62^620^6206D997%%admin.tpl.inc'] = 'aa5b8fc4f074b6edde8015c798521c9b';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'admin.tpl', 22, false),array('function', 'submenulinks', 'admin.tpl', 27, false),)), $this); ?>
<?php
function _smarty_tplfunc_aa5b8fc4f074b6edde8015c798521c9b_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'admin_title'), $this);
}


function _smarty_tplfunc_aa5b8fc4f074b6edde8015c798521c9b_1(&$this)
{
echo translate_smarty(array('id' => 'admin_main_text'), $this);
}



?>
