<?php /* Smarty version 2.6.26, created on 2010-02-16 14:51:50
         compiled from rss/event_will_start.tpl */

$this->_cache_serials['./Smarty/templates_c/%%62^62A^62A4CFA4%%event_will_start.tpl.inc'] = 'd749dfd611b188189db9a4e805e8d522';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'rss/event_will_start.tpl', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_d749dfd611b188189db9a4e805e8d522_0(&$this)
{
echo translate_smarty(array('id' => 'rss_event_start'), $this);
}


function _smarty_tplfunc_d749dfd611b188189db9a4e805e8d522_1(&$this)
{
echo translate_smarty(array('id' => 'rss_event_start_text','arguments' => $this->_tpl_vars['item']), $this);
}



?>
