<?php /* Smarty version 2.6.26, created on 2010-02-17 19:17:02
         compiled from sitemanagement.tpl */

$this->_cache_serials['./Smarty/templates_c/%%65^651^651E32EE%%sitemanagement.tpl.inc'] = '755e429c01a0045da2e1d189b8167cc0';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'sitemanagement.tpl', 22, false),array('function', 'submenulinks', 'sitemanagement.tpl', 26, false),)), $this); ?>
<?php
function _smarty_tplfunc_755e429c01a0045da2e1d189b8167cc0_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'sitemanagement_title'), $_smarty);
}


function _smarty_tplfunc_755e429c01a0045da2e1d189b8167cc0_1(&$_smarty)
{
echo translate_smarty(array('id' => 'admin_main_text'), $_smarty);
}



?>
