<?php /* Smarty version 2.6.26, created on 2010-02-15 18:31:19
         compiled from error.tpl */

$this->_cache_serials['./Smarty/templates_c/%%67^67E^67E1C58E%%error.tpl.inc'] = 'fcd7ba3fd4f44cdc54bfb23027ff0a6e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'error.tpl', 22, false),array('modifier', 'escape', 'error.tpl', 32, false),array('modifier', 'nl2br', 'error.tpl', 41, false),)), $this); ?>
<?php
function _smarty_tplfunc_fcd7ba3fd4f44cdc54bfb23027ff0a6e_0(&$_smarty)
{
echo translate_smarty(array('id' => $_smarty->_tpl_vars['error']->title,'assign' => 'title'), $_smarty);
}


function _smarty_tplfunc_fcd7ba3fd4f44cdc54bfb23027ff0a6e_1(&$_smarty)
{
echo translate_smarty(array('id' => 'error_occured'), $_smarty);
}


function _smarty_tplfunc_fcd7ba3fd4f44cdc54bfb23027ff0a6e_2(&$_smarty)
{
echo translate_smarty(array('id' => 'error_nowwhat'), $_smarty);
}



?>
