<?php /* Smarty version 2.6.26, created on 2010-02-16 14:40:11
         compiled from editclass.tpl */

$this->_cache_serials['./Smarty/templates_c/%%67^674^67461357%%editclass.tpl.inc'] = 'e26993a9303581d73f3c44c63d0b417e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editclass.tpl', 22, false),array('function', 'formerror', 'editclass.tpl', 34, false),array('function', 'html_options', 'editclass.tpl', 51, false),array('modifier', 'escape', 'editclass.tpl', 33, false),)), $this); ?>
<?php
function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'editclass_title'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_1(&$_smarty)
{
echo translate_smarty(array('id' => 'editclass_title'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_2(&$_smarty)
{
echo translate_smarty(array('id' => 'name'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_3(&$_smarty)
{
echo formerror_smarty(array('field' => 'Name'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_4(&$_smarty)
{
echo translate_smarty(array('id' => 'minage'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_5(&$_smarty)
{
echo formerror_smarty(array('field' => 'MinimumAge'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_6(&$_smarty)
{
echo translate_smarty(array('id' => 'maxage'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_7(&$_smarty)
{
echo formerror_smarty(array('field' => 'MaximumAge'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_8(&$_smarty)
{
echo translate_smarty(array('id' => 'gender'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_9(&$_smarty)
{
echo translate_smarty(array('id' => 'available'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_10(&$_smarty)
{
echo translate_smarty(array('id' => 'form_save'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_11(&$_smarty)
{
echo translate_smarty(array('id' => 'form_cancel'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_12(&$_smarty)
{
echo translate_smarty(array('id' => 'delete_class'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_13(&$_smarty)
{
echo translate_smarty(array('id' => 'can_delete_class'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_14(&$_smarty)
{
echo translate_smarty(array('id' => 'delete'), $_smarty);
}


function _smarty_tplfunc_e26993a9303581d73f3c44c63d0b417e_15(&$_smarty)
{
echo translate_smarty(array('id' => 'cant_delete_class'), $_smarty);
}



?>
