<?php /* Smarty version 2.6.26, created on 2010-02-16 14:40:09
         compiled from manageclasses.tpl */

$this->_cache_serials['./Smarty/templates_c/%%6A^6AB^6ABC7877%%manageclasses.tpl.inc'] = '29dac2f0abfd6e5c1b4b4b59af35b4ba';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'manageclasses.tpl', 22, false),array('function', 'url', 'manageclasses.tpl', 25, false),array('modifier', 'escape', 'manageclasses.tpl', 38, false),)), $this); ?>
<?php
function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'manageclasses_title'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_1(&$_smarty)
{
echo url_smarty(array('page' => 'editclass','id' => 'new'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_2(&$_smarty)
{
echo translate_smarty(array('id' => 'new_class'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_3(&$_smarty)
{
echo translate_smarty(array('id' => 'name'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_4(&$_smarty)
{
echo translate_smarty(array('id' => 'minage'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_5(&$_smarty)
{
echo translate_smarty(array('id' => 'maxage'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_6(&$_smarty)
{
echo translate_smarty(array('id' => 'gender'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_7(&$_smarty)
{
echo translate_smarty(array('id' => 'available'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_8(&$_smarty)
{
echo translate_smarty(array('id' => 'edit'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_9(&$_smarty)
{
echo translate_smarty(array('id' => 'male'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_10(&$_smarty)
{
echo translate_smarty(array('id' => 'female'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_11(&$_smarty)
{
echo translate_smarty(array('id' => 'any'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_12(&$_smarty)
{
echo translate_smarty(array('id' => "yes!"), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_13(&$_smarty)
{
echo translate_smarty(array('id' => 'not'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_14(&$_smarty)
{
echo url_smarty(array('page' => 'editclass','id' => $_smarty->_tpl_vars['class']->id), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_15(&$_smarty)
{
echo translate_smarty(array('id' => 'edit'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_16(&$_smarty)
{
echo url_smarty(array('page' => 'editclass','id' => 'new'), $_smarty);
}


function _smarty_tplfunc_29dac2f0abfd6e5c1b4b4b59af35b4ba_17(&$_smarty)
{
echo translate_smarty(array('id' => 'new_class'), $_smarty);
}



?>
