<?php /* Smarty version 2.6.26, created on 2010-02-16 12:45:26
         compiled from login.tpl */

$this->_cache_serials['./Smarty/templates_c/%%6A^6A5^6A537DD8%%login.tpl.inc'] = '7672f398bbc969f1a5b0febda93ed3c4';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'login.tpl', 22, false),array('function', 'url', 'login.tpl', 53, false),array('modifier', 'escape', 'login.tpl', 39, false),)), $this); ?>
<?php
function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_0(&$_smarty)
{
echo translate_smarty(array('id' => 'login_title','assign' => 'title'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_1(&$_smarty)
{
echo translate_smarty(array('id' => 'loginform_title'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_2(&$_smarty)
{
echo translate_smarty(array('id' => 'username'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_3(&$_smarty)
{
echo translate_smarty(array('id' => 'password'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_4(&$_smarty)
{
echo translate_smarty(array('id' => 'loginbutton'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_5(&$_smarty)
{
echo url_smarty(array('page' => 'register'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_6(&$_smarty)
{
echo translate_smarty(array('id' => 'register'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_7(&$_smarty)
{
echo url_smarty(array('page' => 'recoverpassword'), $_smarty);
}


function _smarty_tplfunc_7672f398bbc969f1a5b0febda93ed3c4_8(&$_smarty)
{
echo translate_smarty(array('id' => 'forgottenpassword'), $_smarty);
}



?>
