<?php /* Smarty version 2.6.26, created on 2010-02-16 14:56:46
         compiled from editcourse.tpl */

$this->_cache_serials['./Smarty/templates_c/%%6E^6E8^6E883B05%%editcourse.tpl.inc'] = '64bc7280be747d35b0eb7d7cb4d9c93d';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editcourse.tpl', 45, false),array('function', 'initializeGetFormFields', 'editcourse.tpl', 50, false),array('modifier', 'escape', 'editcourse.tpl', 76, false),)), $this); ?>
<?php
function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'editcourse_title'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_1(&$_smarty)
{
echo initializeGetFormFields_Smarty(array(), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_2(&$_smarty)
{
echo translate_smarty(array('id' => 'num_holes'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_3(&$_smarty)
{
echo translate_smarty(array('id' => 'proceed'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_4(&$_smarty)
{
echo translate_smarty(array('id' => 'course_edit_warning'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_5(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_6(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_7(&$_smarty)
{
echo translate_smarty(array('id' => 'delete'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_8(&$_smarty)
{
echo translate_smarty(array('id' => 'course'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_9(&$_smarty)
{
echo translate_smarty(array('id' => 'name'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_10(&$_smarty)
{
echo translate_smarty(array('id' => 'map_url'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_11(&$_smarty)
{
echo translate_smarty(array('id' => 'link'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_12(&$_smarty)
{
echo translate_smarty(array('id' => 'description'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_13(&$_smarty)
{
echo translate_smarty(array('id' => 'holes_list'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_14(&$_smarty)
{
echo translate_smarty(array('id' => 'hole_number'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_15(&$_smarty)
{
echo translate_smarty(array('id' => 'par'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_16(&$_smarty)
{
echo translate_smarty(array('id' => 'hole_length'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_17(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_18(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_64bc7280be747d35b0eb7d7cb4d9c93d_19(&$_smarty)
{
echo translate_smarty(array('id' => 'delete'), $_smarty);
}



?>
