<?php /* Smarty version 2.6.26, created on 2010-02-16 14:43:54
         compiled from editeventpages.tpl */

$this->_cache_serials['./Smarty/templates_c/%%6F^6FD^6FD5B21D%%editeventpages.tpl.inc'] = '0fbb613bb6eb45c837d55384ff6b8233';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editeventpages.tpl', 22, false),array('function', 'submenulinks', 'editeventpages.tpl', 27, false),)), $this); ?>
<?php
function _smarty_tplfunc_0fbb613bb6eb45c837d55384ff6b8233_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'editeventpages_title'), $_smarty);
}


function _smarty_tplfunc_0fbb613bb6eb45c837d55384ff6b8233_1(&$_smarty)
{
echo translate_smarty(array('id' => 'eventpages_main_text'), $_smarty);
}



?>
