<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:08
         compiled from javascript/tablesearch.tpl */

$this->_cache_serials['./Smarty/templates_c/%%70^701^701558F2%%tablesearch.tpl.inc'] = '0187971e7d3d7c7c4bb07e9bad949eb2';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'javascript/tablesearch.tpl', 51, false),)), $this); ?>
<?php
function _smarty_tplfunc_0187971e7d3d7c7c4bb07e9bad949eb2_0(&$this)
{
echo translate_smarty(array('id' => 'Restore_AutoSearch'), $this);
}



?>
