<?php /* Smarty version 2.6.26, created on 2010-02-15 16:10:49
         compiled from confirm_event_delete.tpl */

$this->_cache_serials['./Smarty/templates_c/%%73^731^7318CCF0%%confirm_event_delete.tpl.inc'] = '26f8abd82047757b5c62687d49929e3f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'confirm_event_delete.tpl', 25, false),array('modifier', 'escape', 'confirm_event_delete.tpl', 37, false),)), $this); ?>
<?php
function _smarty_tplfunc_26f8abd82047757b5c62687d49929e3f_0(&$this)
{
echo translate_smarty(array('id' => 'confirm_event_delete'), $this);
}


function _smarty_tplfunc_26f8abd82047757b5c62687d49929e3f_1(&$this)
{
echo translate_smarty(array('id' => 'confirm_event_delete_text'), $this);
}


function _smarty_tplfunc_26f8abd82047757b5c62687d49929e3f_2(&$this)
{
echo translate_smarty(array('id' => 'confirm_event_delete_question'), $this);
}


function _smarty_tplfunc_26f8abd82047757b5c62687d49929e3f_3(&$this)
{
echo translate_smarty(array('id' => 'delete'), $this);
}


function _smarty_tplfunc_26f8abd82047757b5c62687d49929e3f_4(&$this)
{
echo translate_smarty(array('id' => 'abort'), $this);
}



?>
