<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:24
         compiled from redirect.tpl */

$this->_cache_serials['./Smarty/templates_c/%%77^770^770CF2DB%%redirect.tpl.inc'] = '5869ee6f0a11d0638914e7236bad9064';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'redirect.tpl', 23, false),array('modifier', 'escape', 'redirect.tpl', 31, false),)), $this); ?>
<?php
function _smarty_tplfunc_5869ee6f0a11d0638914e7236bad9064_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'loginredirect_title'), $this);
}


function _smarty_tplfunc_5869ee6f0a11d0638914e7236bad9064_1(&$this)
{
echo translate_smarty(array('assign' => 'text','id' => 'loginredirect_text'), $this);
}


function _smarty_tplfunc_5869ee6f0a11d0638914e7236bad9064_2(&$this)
{
echo translate_smarty(array('id' => 'redirect_proceed'), $this);
}



?>
