<?php /* Smarty version 2.6.26, created on 2010-02-16 14:59:31
         compiled from editgroups.tpl */

$this->_cache_serials['./Smarty/templates_c/%%7B^7B0^7B043DB8%%editgroups.tpl.inc'] = '3bfe3c676f709288a2325bc7a2416eb8';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editgroups.tpl', 22, false),array('function', 'initializeGetFormFields', 'editgroups.tpl', 127, false),array('function', 'math', 'editgroups.tpl', 176, false),array('function', 'counter', 'editgroups.tpl', 182, false),array('modifier', 'escape', 'editgroups.tpl', 157, false),)), $this); ?>
<?php
function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_0(&$_smarty)
{
echo translate_smarty(array('id' => 'editgroups_title','assign' => 'title'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_1(&$_smarty)
{
echo initializeGetFormFields_Smarty(array('regenerate' => false), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_2(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_groups_text_2'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_3(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_groups'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_4(&$_smarty)
{
echo initializeGetFormFields_Smarty(array('regenerate' => false), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_5(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_groups_text_1'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_6(&$_smarty)
{
echo translate_smarty(array('id' => 'regenerate_groups'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_7(&$_smarty)
{
echo translate_smarty(array('id' => 'edit_groups_quickhelp'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_8(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_9(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_10(&$_smarty)
{
echo translate_smarty(array('id' => 'rebalance_groups'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_11(&$_smarty)
{
echo translate_smarty(array('id' => 'groups_finished'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_12(&$_smarty)
{
echo translate_smarty(array('id' => 'group_number','number' => $_smarty->_tpl_vars['group']['PoolNumber']), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_13(&$_smarty)
{
echo translate_smarty(array('id' => 'change_hole'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_14(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_15(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_16(&$_smarty)
{
echo translate_smarty(array('id' => 'groups_finished'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_17(&$_smarty)
{
echo translate_smarty(array('id' => 'error_cant_tag_another'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_18(&$_smarty)
{
echo translate_smarty(array('id' => 'error_cant_tag_different_type'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_19(&$_smarty)
{
echo translate_smarty(array('id' => 'move_tagged_object_here'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_20(&$_smarty)
{
echo translate_smarty(array('id' => 'error_cant_move_between_sections'), $_smarty);
}


function _smarty_tplfunc_3bfe3c676f709288a2325bc7a2416eb8_21(&$_smarty)
{
echo translate_smarty(array('id' => 'change_hole_prompt'), $_smarty);
}



?>
