<?php /* Smarty version 2.6.26, created on 2010-02-17 19:13:46
         compiled from enterresults.tpl */

$this->_cache_serials['./Smarty/templates_c/%%8E^8E6^8E67F795%%enterresults.tpl.inc'] = '2dbd8beeadbfa503241b6861d0a0be35';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'enterresults.tpl', 103, false),array('function', 'url', 'enterresults.tpl', 187, false),array('modifier', 'escape', 'enterresults.tpl', 155, false),)), $this); ?>
<?php
function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_0(&$_smarty)
{
echo translate_smarty(array('id' => 'page_requires_javascript'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_1(&$_smarty)
{
echo translate_smarty(array('id' => 'toggle_menu'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_2(&$_smarty)
{
echo translate_smarty(array('id' => 'inline_search_help'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_3(&$_smarty)
{
echo translate_smarty(array('id' => 'button_goto'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_4(&$_smarty)
{
echo translate_smarty(array('id' => 'search_results'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_5(&$_smarty)
{
echo translate_smarty(array('id' => 'result_search_extrahelp'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_6(&$_smarty)
{
echo translate_smarty(array('id' => 'result_group'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_7(&$_smarty)
{
echo translate_smarty(array('id' => 'result_name'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_8(&$_smarty)
{
echo translate_smarty(array('id' => 'result_pdga'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_9(&$_smarty)
{
echo translate_smarty(array('id' => 'hole_num'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_10(&$_smarty)
{
echo translate_smarty(array('id' => 'hole_par'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_11(&$_smarty)
{
echo translate_smarty(array('id' => 'result_penalty'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_12(&$_smarty)
{
echo translate_smarty(array('id' => 'result_suddendeath'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_13(&$_smarty)
{
echo translate_smarty(array('id' => 'result_total'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_14(&$_smarty)
{
echo translate_smarty(array('id' => 'event_save'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_15(&$_smarty)
{
echo translate_smarty(array('id' => 'all_ready'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_16(&$_smarty)
{
echo url_smarty(array('page' => "javascript/live"), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_17(&$_smarty)
{
echo translate_smarty(array('id' => 'all_ready'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_18(&$_smarty)
{
echo url_smarty(array('page' => 'liveresultdata'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_19(&$_smarty)
{
echo translate_smarty(array('id' => 'save_failed'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_20(&$_smarty)
{
echo url_smarty(array('page' => 'event','id' => $_GET['id'],'view' => 'leaderboard'), $_smarty);
}


function _smarty_tplfunc_2dbd8beeadbfa503241b6861d0a0be35_21(&$_smarty)
{
echo translate_smarty(array('id' => 'button_ready'), $_smarty);
}



?>
