<?php /* Smarty version 2.6.26, created on 2010-02-16 13:06:29
         compiled from termsandconditions.tpl */

$this->_cache_serials['./Smarty/templates_c/%%90^903^9037E22E%%termsandconditions.tpl.inc'] = '9227ade90810a5a48f7bf2efd202a0b7';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'termsandconditions.tpl', 28, false),)), $this); ?>
<?php
function _smarty_tplfunc_9227ade90810a5a48f7bf2efd202a0b7_0(&$_smarty)
{
echo translate_smarty(array('id' => 'terms_and_conditions'), $_smarty);
}


function _smarty_tplfunc_9227ade90810a5a48f7bf2efd202a0b7_1(&$_smarty)
{
echo translate_smarty(array('id' => 'site_name'), $_smarty);
}



?>
