<?php /* Smarty version 2.6.26, created on 2010-02-04 08:07:52
         compiled from user_edit_done.tpl */

$this->_cache_serials['./Smarty/templates_c/%%92^92F^92FF9E4E%%user_edit_done.tpl.inc'] = 'dd59d12ab807a6ffcd57bd54b8893e71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'user_edit_done.tpl', 4, false),)), $this); ?>
<?php
function _smarty_tplfunc_dd59d12ab807a6ffcd57bd54b8893e71_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'user_edit_done'), $this);
}


function _smarty_tplfunc_dd59d12ab807a6ffcd57bd54b8893e71_1(&$this)
{
echo translate_smarty(array('id' => 'user_edit_done_main_text'), $this);
}



?>
