<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:08
         compiled from javascript/formvalidation.tpl */

$this->_cache_serials['./Smarty/templates_c/%%9B^9B3^9B32DF5C%%formvalidation.tpl.inc'] = 'ff8c0b26f9f07fa2595979b0a1f21ae9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'javascript/formvalidation.tpl', 119, false),)), $this); ?>
<?php
function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_0(&$this)
{
echo translate_smarty(array('id' => 'FormError_Summary','escape' => false), $this);
}


function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_1(&$this)
{
echo translate_smarty(array('id' => 'FormError_NotEmpty','escape' => false), $this);
}


function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_2(&$this)
{
echo translate_smarty(array('id' => 'FormError_InvalidEmail','escape' => false), $this);
}


function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_3(&$this)
{
echo translate_smarty(array('id' => 'FormError_PasswordsDontMatch','escape' => false), $this);
}


function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_4(&$this)
{
echo translate_smarty(array('id' => 'FormError_NotPositiveInteger','escape' => false), $this);
}


function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_5(&$this)
{
echo translate_smarty(array('id' => 'FormError_NotEmpty','escape' => false), $this);
}


function _smarty_tplfunc_ff8c0b26f9f07fa2595979b0a1f21ae9_6(&$this)
{
echo translate_smarty(array('id' => 'FormError_Default'), $this);
}



?>
