<?php /* Smarty version 2.6.26, created on 2010-02-17 19:16:49
         compiled from edittournament.tpl */

$this->_cache_serials['./Smarty/templates_c/%%9C^9CE^9CEE1763%%edittournament.tpl.inc'] = '6bcc16a3b5f1e02f97b53cdb157cc24c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'edittournament.tpl', 41, false),array('function', 'formerror', 'edittournament.tpl', 53, false),array('function', 'html_options', 'edittournament.tpl', 65, false),array('modifier', 'escape', 'edittournament.tpl', 52, false),)), $this); ?>
<?php
function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'edittournament_title'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_1(&$_smarty)
{
echo translate_smarty(array('id' => 'edittournament_title'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_2(&$_smarty)
{
echo translate_smarty(array('id' => 'name'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_3(&$_smarty)
{
echo formerror_smarty(array('field' => 'name'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_4(&$_smarty)
{
echo translate_smarty(array('id' => 'year'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_5(&$_smarty)
{
echo formerror_smarty(array('field' => 'year'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_6(&$_smarty)
{
echo translate_smarty(array('id' => 'scorecalculation'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_7(&$_smarty)
{
echo translate_smarty(array('id' => 'level'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_8(&$_smarty)
{
echo translate_smarty(array('id' => 'available'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_9(&$_smarty)
{
echo translate_smarty(array('id' => 'delete_tournament'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_10(&$_smarty)
{
echo translate_smarty(array('id' => 'can_delete_tournament'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_11(&$_smarty)
{
echo translate_smarty(array('id' => 'delete'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_12(&$_smarty)
{
echo translate_smarty(array('id' => 'cant_delete_tournament'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_13(&$_smarty)
{
echo translate_smarty(array('id' => 'description'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_14(&$_smarty)
{
echo translate_smarty(array('id' => 'form_save'), $_smarty);
}


function _smarty_tplfunc_6bcc16a3b5f1e02f97b53cdb157cc24c_15(&$_smarty)
{
echo translate_smarty(array('id' => 'form_cancel'), $_smarty);
}



?>
