<?php /* Smarty version 2.6.26, created on 2010-02-19 00:49:44
         compiled from rss/signup.tpl */

$this->_cache_serials['./Smarty/templates_c/%%AD^AD3^AD3E91B7%%signup.tpl.inc'] = '037de05b25b5d6c3447144ceb9f48d4c';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'rss/signup.tpl', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_037de05b25b5d6c3447144ceb9f48d4c_0(&$this)
{
echo translate_smarty(array('id' => $this->_tpl_vars['titleid'],'arguments' => $this->_tpl_vars['item']), $this);
}


function _smarty_tplfunc_037de05b25b5d6c3447144ceb9f48d4c_1(&$this)
{
echo translate_smarty(array('id' => $this->_tpl_vars['textid'],'arguments' => $this->_tpl_vars['item']), $this);
}



?>
