<?php /* Smarty version 2.6.26, created on 2010-02-16 14:46:58
         compiled from eventviews/payment.tpl */

$this->_cache_serials['./Smarty/templates_c/%%BA^BAE^BAE1D1F7%%payment.tpl.inc'] = 'f44697c4691805ff0c398a8fec0bcb84';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'eventviews/payment.tpl', 28, false),)), $this); ?>
<?php
function _smarty_tplfunc_f44697c4691805ff0c398a8fec0bcb84_0(&$_smarty)
{
echo translate_smarty(array('id' => 'login_to_sign_up'), $_smarty);
}


function _smarty_tplfunc_f44697c4691805ff0c398a8fec0bcb84_1(&$_smarty)
{
echo translate_smarty(array('id' => 'not_signed_up_nothere'), $_smarty);
}


function _smarty_tplfunc_f44697c4691805ff0c398a8fec0bcb84_2(&$_smarty)
{
echo translate_smarty(array('id' => 'signed_up_and_paid'), $_smarty);
}


function _smarty_tplfunc_f44697c4691805ff0c398a8fec0bcb84_3(&$_smarty)
{
echo translate_smarty(array('id' => 'signed_up_not_paid'), $_smarty);
}



?>
