<?php /* Smarty version 2.6.26, created on 2010-02-16 14:56:37
         compiled from managecourses.tpl */

$this->_cache_serials['./Smarty/templates_c/%%BC^BC0^BC0DD097%%managecourses.tpl.inc'] = 'a379db7967275fcdecd975e75e920eed';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'managecourses.tpl', 22, false),array('function', 'url', 'managecourses.tpl', 26, false),array('modifier', 'escape', 'managecourses.tpl', 39, false),)), $this); ?>
<?php
function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'managecourses_title'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_1(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => 'new','event' => $_GET['id']), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_2(&$_smarty)
{
echo translate_smarty(array('id' => 'new_course'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_3(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => 'new'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_4(&$_smarty)
{
echo translate_smarty(array('id' => 'new_course'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_5(&$_smarty)
{
echo translate_smarty(array('id' => 'name'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_6(&$_smarty)
{
echo translate_smarty(array('id' => 'edit'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_7(&$_smarty)
{
echo translate_smarty(array('id' => 'copy'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_8(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => $_smarty->_tpl_vars['course']['id'],'event' => $_GET['id']), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_9(&$_smarty)
{
echo translate_smarty(array('id' => 'edit'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_10(&$_smarty)
{
echo translate_smarty(array('id' => 'edit_blocked'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_11(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => $_smarty->_tpl_vars['course']['id']), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_12(&$_smarty)
{
echo translate_smarty(array('id' => 'edit'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_13(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => 'new','template' => $_smarty->_tpl_vars['course']['id'],'event' => $_GET['id']), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_14(&$_smarty)
{
echo translate_smarty(array('id' => 'copy'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_15(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => 'new','template' => $_smarty->_tpl_vars['course']['id']), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_16(&$_smarty)
{
echo translate_smarty(array('id' => 'copy'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_17(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => 'new','event' => $_GET['id']), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_18(&$_smarty)
{
echo translate_smarty(array('id' => 'new_course'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_19(&$_smarty)
{
echo url_smarty(array('page' => 'editcourse','id' => 'new'), $_smarty);
}


function _smarty_tplfunc_a379db7967275fcdecd975e75e920eed_20(&$_smarty)
{
echo translate_smarty(array('id' => 'new_course'), $_smarty);
}



?>
