<?php /* Smarty version 2.6.26, created on 2010-02-15 16:25:12
         compiled from include/languagebar.tpl */

$this->_cache_serials['./Smarty/templates_c/%%BC^BCB^BCB89A5D%%languagebar.tpl.inc'] = '6a72dcdb82a027ebbb688fd2814e0982';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'include/languagebar.tpl', 39, false),)), $this); ?>
<?php
function _smarty_tplfunc_6a72dcdb82a027ebbb688fd2814e0982_0(&$this)
{
echo translate_smarty(array('id' => "language-fi-FI"), $this);
}


function _smarty_tplfunc_6a72dcdb82a027ebbb688fd2814e0982_1(&$this)
{
echo translate_smarty(array('id' => "language-fi-FI"), $this);
}


function _smarty_tplfunc_6a72dcdb82a027ebbb688fd2814e0982_2(&$this)
{
echo translate_smarty(array('id' => "language-sv"), $this);
}


function _smarty_tplfunc_6a72dcdb82a027ebbb688fd2814e0982_3(&$this)
{
echo translate_smarty(array('id' => "language-sv"), $this);
}



?>
