<?php /* Smarty version 2.6.26, created on 2010-02-18 20:13:54
         compiled from starttimes.tpl */

$this->_cache_serials['./Smarty/templates_c/%%C1^C10^C10C5B62%%starttimes.tpl.inc'] = 'd6e04c4d8e27e83ebc3e1dbdd293dea9';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'starttimes.tpl', 22, false),array('modifier', 'date_format', 'starttimes.tpl', 126, false),array('modifier', 'escape', 'starttimes.tpl', 127, false),)), $this); ?>
<?php
function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_0(&$this)
{
echo translate_smarty(array('id' => 'starttimes_title','assign' => 'title'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_1(&$this)
{
echo translate_smarty(array('id' => 'page_requires_javascript'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_2(&$this)
{
echo translate_smarty(array('id' => 'starttimes_help'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_3(&$this)
{
echo translate_smarty(array('id' => 'round_starts_at','start' => $this->_tpl_vars['startTime'],'interval' => $this->_tpl_vars['interval']), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_4(&$this)
{
echo translate_smarty(array('id' => 'save'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_5(&$this)
{
echo translate_smarty(array('id' => 'cancel'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_6(&$this)
{
echo translate_smarty(array('id' => 'start_time'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_7(&$this)
{
echo translate_smarty(array('id' => 'forced'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_8(&$this)
{
echo translate_smarty(array('id' => 'automatic'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_9(&$this)
{
echo translate_smarty(array('id' => 'change_start_time'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_10(&$this)
{
echo translate_smarty(array('id' => 'estimated_number_of_groups','estimate' => $this->_tpl_vars['estimate']), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_11(&$this)
{
echo translate_smarty(array('id' => 'class_present'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_12(&$this)
{
echo translate_smarty(array('id' => 'earlier'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_13(&$this)
{
echo translate_smarty(array('id' => 'later'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_14(&$this)
{
echo translate_smarty(array('id' => 'save'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_15(&$this)
{
echo translate_smarty(array('id' => 'cancel'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_16(&$this)
{
echo translate_smarty(array('id' => 'change_time_prompt'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_17(&$this)
{
echo translate_smarty(array('id' => 'automatic'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_18(&$this)
{
echo translate_smarty(array('id' => 'forced'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_19(&$this)
{
echo translate_smarty(array('id' => 'invalid_time'), $this);
}


function _smarty_tplfunc_d6e04c4d8e27e83ebc3e1dbdd293dea9_20(&$this)
{
echo translate_smarty(array('id' => 'section_not_present'), $this);
}



?>
