<?php /* Smarty version 2.6.26, created on 2010-02-13 13:10:33
         compiled from rss/event_start_today.tpl */

$this->_cache_serials['./Smarty/templates_c/%%C3^C35^C350BCB7%%event_start_today.tpl.inc'] = '120aee27eb0a6efea07c6d6464c15b9f';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'rss/event_start_today.tpl', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_120aee27eb0a6efea07c6d6464c15b9f_0(&$this)
{
echo translate_smarty(array('id' => 'rss_event_start_today'), $this);
}


function _smarty_tplfunc_120aee27eb0a6efea07c6d6464c15b9f_1(&$this)
{
echo translate_smarty(array('id' => 'rss_event_start_today_text','arguments' => $this->_tpl_vars['item']), $this);
}



?>
