<?php /* Smarty version 2.6.26, created on 2010-02-16 14:54:39
         compiled from managerounds.tpl */

$this->_cache_serials['./Smarty/templates_c/%%D5^D57^D57954C4%%managerounds.tpl.inc'] = '5dd4cc673e5ae49e663133a537215a2e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'managerounds.tpl', 22, false),array('function', 'url', 'managerounds.tpl', 27, false),array('function', 'counter', 'managerounds.tpl', 36, false),array('function', 'math', 'managerounds.tpl', 38, false),array('modifier', 'date_format', 'managerounds.tpl', 45, false),array('modifier', 'escape', 'managerounds.tpl', 75, false),)), $this); ?>
<?php
function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_0(&$_smarty)
{
echo translate_smarty(array('assign' => 'title','id' => 'managerounds_title'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_1(&$_smarty)
{
echo url_smarty(array('page' => 'managecourses','id' => $_GET['id']), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_2(&$_smarty)
{
echo translate_smarty(array('id' => 'round_course_edit_help','link' => $_smarty->_tpl_vars['link']), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_3(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_4(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_5(&$_smarty)
{
echo translate_smarty(array('id' => 'round_number','number' => $_smarty->_tpl_vars['number']), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_6(&$_smarty)
{
echo translate_smarty(array('id' => 'date'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_7(&$_smarty)
{
echo translate_smarty(array('id' => 'starttype'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_8(&$_smarty)
{
echo translate_smarty(array('id' => 'sequential'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_9(&$_smarty)
{
echo translate_smarty(array('id' => 'simultaneous'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_10(&$_smarty)
{
echo translate_smarty(array('id' => 'group_interval'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_11(&$_smarty)
{
echo translate_smarty(array('id' => 'round_valid'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_12(&$_smarty)
{
echo translate_smarty(array('id' => 'round_course'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_13(&$_smarty)
{
echo translate_smarty(array('id' => 'select_none'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_14(&$_smarty)
{
echo translate_smarty(array('id' => 'save'), $_smarty);
}


function _smarty_tplfunc_5dd4cc673e5ae49e663133a537215a2e_15(&$_smarty)
{
echo translate_smarty(array('id' => 'cancel'), $_smarty);
}



?>
