<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:32
         compiled from editad.tpl */

$this->_cache_serials['./Smarty/templates_c/%%D5^D57^D57C7934%%editad.tpl.inc'] = 'e5c576800db88c9c04f36e695e2f0514';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'editad.tpl', 22, false),array('function', 'html_options', 'editad.tpl', 112, false),array('modifier', 'escape', 'editad.tpl', 50, false),)), $this); ?>
<?php
function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_0(&$this)
{
echo translate_smarty(array('assign' => 'title','id' => 'editad_title'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_1(&$this)
{
echo translate_smarty(array('assign' => 'typetext','id' => $this->_tpl_vars['locid']), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_2(&$this)
{
echo translate_smarty(array('id' => 'ad_inline_help','adtype' => $this->_tpl_vars['typetext']), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_3(&$this)
{
echo translate_smarty(array('id' => 'page_requires_javascript'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_4(&$this)
{
echo translate_smarty(array('id' => 'ad_type_heading'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_5(&$this)
{
echo translate_smarty(array('id' => 'ad_type_eventdefault'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_6(&$this)
{
echo translate_smarty(array('id' => 'ad_type_default'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_7(&$this)
{
echo translate_smarty(array('id' => 'ad_type_imageandlink'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_8(&$this)
{
echo translate_smarty(array('id' => 'ad_type_html'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_9(&$this)
{
echo translate_smarty(array('id' => 'ad_type_reference'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_10(&$this)
{
echo translate_smarty(array('id' => 'ad_type_disabled'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_11(&$this)
{
echo translate_smarty(array('id' => 'ad_details_heading'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_12(&$this)
{
echo translate_smarty(array('id' => 'ad_eventdefault_description'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_13(&$this)
{
echo translate_smarty(array('id' => 'ad_default_description'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_14(&$this)
{
echo translate_smarty(array('id' => 'ad_disabled_description'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_15(&$this)
{
echo translate_smarty(array('id' => 'ad_html_description'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_16(&$this)
{
echo translate_smarty(array('id' => 'ad_imageandlink_description'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_17(&$this)
{
echo translate_smarty(array('id' => 'ad_link'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_18(&$this)
{
echo translate_smarty(array('id' => 'ad_image'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_19(&$this)
{
echo translate_smarty(array('id' => 'ad_select'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_20(&$this)
{
echo translate_smarty(array('id' => 'ad_upload'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_21(&$this)
{
echo translate_smarty(array('id' => 'ad_link'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_22(&$this)
{
echo translate_smarty(array('id' => 'ad_reference_description'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_23(&$this)
{
echo translate_smarty(array('id' => $this->_tpl_vars['locid']), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_24(&$this)
{
echo translate_smarty(array('id' => $this->_tpl_vars['locid']), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_25(&$this)
{
echo translate_smarty(array('id' => 'save'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_26(&$this)
{
echo translate_smarty(array('id' => 'preview'), $this);
}


function _smarty_tplfunc_e5c576800db88c9c04f36e695e2f0514_27(&$this)
{
echo translate_smarty(array('id' => 'cancel'), $this);
}



?>
