<?php /* Smarty version 2.6.26, created on 2010-02-16 14:50:37
         compiled from support/eventlockhelper.tpl */

$this->_cache_serials['./Smarty/templates_c/%%E6^E6B^E6BAC402%%eventlockhelper.tpl.inc'] = '19a99f468d3aae11bbaa7bc7647a0ca1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'support/eventlockhelper.tpl', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_19a99f468d3aae11bbaa7bc7647a0ca1_0(&$_smarty)
{
echo translate_smarty(array('id' => 'event_is_locked_cant_edit'), $_smarty);
}



?>
