<?php /* Smarty version 2.6.26, created on 2010-02-16 14:46:23
         compiled from eventviews/course.tpl */

$this->_cache_serials['./Smarty/templates_c/%%EB^EB4^EB4697D3%%course.tpl.inc'] = '9ecb12720bd72fc51fab7500928fdaa1';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('modifier', 'escape', 'eventviews/course.tpl', 29, false),array('function', 'translate', 'eventviews/course.tpl', 32, false),)), $this); ?>
<?php
function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_0(&$_smarty)
{
echo translate_smarty(array('id' => 'course_details'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_1(&$_smarty)
{
echo translate_smarty(array('id' => 'course_map'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_2(&$_smarty)
{
echo translate_smarty(array('id' => 'holes_title'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_3(&$_smarty)
{
echo translate_smarty(array('id' => 'holeNumber'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_4(&$_smarty)
{
echo translate_smarty(array('id' => 'par'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_5(&$_smarty)
{
echo translate_smarty(array('id' => 'length'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_6(&$_smarty)
{
echo translate_smarty(array('id' => 'holeNumber'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_7(&$_smarty)
{
echo translate_smarty(array('id' => 'par'), $_smarty);
}


function _smarty_tplfunc_9ecb12720bd72fc51fab7500928fdaa1_8(&$_smarty)
{
echo translate_smarty(array('id' => 'length'), $_smarty);
}



?>
