<?php /* Smarty version 2.6.26, created on 2010-02-19 00:49:46
         compiled from rss/signupend.tpl */

$this->_cache_serials['./Smarty/templates_c/%%EE^EE9^EE94A259%%signupend.tpl.inc'] = '0e01f3d2cee181bf24160cb827ca972e';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'rss/signupend.tpl', 24, false),)), $this); ?>
<?php
function _smarty_tplfunc_0e01f3d2cee181bf24160cb827ca972e_0(&$this)
{
echo translate_smarty(array('id' => $this->_tpl_vars['titleid'],'arguments' => $this->_tpl_vars['item']), $this);
}


function _smarty_tplfunc_0e01f3d2cee181bf24160cb827ca972e_1(&$this)
{
echo translate_smarty(array('id' => $this->_tpl_vars['textid'],'arguments' => $this->_tpl_vars['item']), $this);
}



?>
