<?php /* Smarty version 2.6.26, created on 2010-02-15 15:48:08
         compiled from include/submenulevel.tpl */

$this->_cache_serials['./Smarty/templates_c/%%F4^F49^F493750E%%submenulevel.tpl.inc'] = 'c3d6741f17a497411b59f7c6dc8afc71';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'url', 'include/submenulevel.tpl', 27, false),array('modifier', 'escape', 'include/submenulevel.tpl', 30, false),)), $this); ?>
<?php
function _smarty_tplfunc_c3d6741f17a497411b59f7c6dc8afc71_0(&$this)
{
echo url_smarty(array('arguments' => $this->_tpl_vars['item']['link']), $this);
}



?>
