<?php /* Smarty version 2.6.26, created on 2010-03-05 03:27:55
         compiled from rss/event_started.tpl */

$this->_cache_serials['./Smarty/templates_c/%%FD^FDA^FDABE595%%event_started.tpl.inc'] = 'f89102fbc04b7fa3ae3748e723396640';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'rss/event_started.tpl', 22, false),)), $this); ?>
<?php
function _smarty_tplfunc_f89102fbc04b7fa3ae3748e723396640_0(&$this)
{
echo translate_smarty(array('id' => 'rss_event_started'), $this);
}


function _smarty_tplfunc_f89102fbc04b7fa3ae3748e723396640_1(&$this)
{
echo translate_smarty(array('id' => 'rss_event_started_text','arguments' => $this->_tpl_vars['item']), $this);
}



?>
