<?php /* Smarty version 2.6.26, created on 2010-02-16 14:27:34
         compiled from user.tpl */

$this->_cache_serials['./Smarty/templates_c/%%FF^FF1^FF17EB69%%user.tpl.inc'] = '748f8faf554e2864a4b65a6e8f5dcdcb';

?><?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'translate', 'user.tpl', 22, false),array('modifier', 'escape', 'user.tpl', 25, false),)), $this); ?>
<?php
function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_0(&$_smarty)
{
echo translate_smarty(array('id' => 'users_title','assign' => 'title'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_1(&$_smarty)
{
echo translate_smarty(array('id' => 'user_header','user' => ((is_array($_tmp=$_smarty->_tpl_vars['userinfo']->username)) ? $_smarty->_run_mod_handler('escape', true, $_tmp) : smarty_modifier_escape($_tmp))), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_2(&$_smarty)
{
echo translate_smarty(array('id' => 'user_name'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_3(&$_smarty)
{
echo translate_smarty(array('id' => 'user_gender'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_4(&$_smarty)
{
echo translate_smarty(array('id' => $_smarty->_tpl_vars['gendertoken']), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_5(&$_smarty)
{
echo translate_smarty(array('id' => 'user_yearofbirth'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_6(&$_smarty)
{
echo translate_smarty(array('id' => 'user_pdga_number'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_7(&$_smarty)
{
echo translate_smarty(array('id' => 'user_not_player'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_8(&$_smarty)
{
echo translate_smarty(array('id' => 'user_pdga_link'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_9(&$_smarty)
{
echo translate_smarty(array('id' => 'user_membershipfee'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_10(&$_smarty)
{
echo translate_smarty(array('id' => 'user_ispaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_11(&$_smarty)
{
echo translate_smarty(array('id' => 'user_notpaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_12(&$_smarty)
{
echo translate_smarty(array('id' => 'user_licensefee'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_13(&$_smarty)
{
echo translate_smarty(array('id' => 'user_ispaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_14(&$_smarty)
{
echo translate_smarty(array('id' => 'user_notpaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_15(&$_smarty)
{
echo translate_smarty(array('id' => 'user_membershipfee'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_16(&$_smarty)
{
echo translate_smarty(array('id' => 'user_ispaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_17(&$_smarty)
{
echo translate_smarty(array('id' => 'user_notpaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_18(&$_smarty)
{
echo translate_smarty(array('id' => 'user_licensefee'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_19(&$_smarty)
{
echo translate_smarty(array('id' => 'user_ispaid'), $_smarty);
}


function _smarty_tplfunc_748f8faf554e2864a4b65a6e8f5dcdcb_20(&$_smarty)
{
echo translate_smarty(array('id' => 'user_notpaid'), $_smarty);
}



?>
